-- ============================================================
-- Seed: Populate domain_intelligence from hardcoded DOMAIN_MAP
-- Idempotent via ON CONFLICT DO NOTHING
-- ============================================================

INSERT INTO domain_intelligence (domain, domain_type, default_category, common_topics, save_count) VALUES
-- Development
('github.com', 'platform', 'Development', ARRAY['open-source'], 1),
('gitlab.com', 'platform', 'Development', ARRAY['open-source'], 1),
('bitbucket.org', 'platform', 'Development', ARRAY[]::TEXT[], 1),
('stackoverflow.com', 'qa', 'Development', ARRAY[]::TEXT[], 1),
('stackexchange.com', 'qa', 'Development', ARRAY[]::TEXT[], 1),
('npmjs.com', 'registry', 'Development', ARRAY[]::TEXT[], 1),
('pypi.org', 'registry', 'Development', ARRAY[]::TEXT[], 1),
('crates.io', 'registry', 'Development', ARRAY[]::TEXT[], 1),
('rubygems.org', 'registry', 'Development', ARRAY[]::TEXT[], 1),
('packagist.org', 'registry', 'Development', ARRAY[]::TEXT[], 1),
('dev.to', 'blog', 'Development', ARRAY[]::TEXT[], 1),
('hashnode.dev', 'blog', 'Development', ARRAY[]::TEXT[], 1),
('codepen.io', 'playground', 'Development', ARRAY[]::TEXT[], 1),
('codesandbox.io', 'playground', 'Development', ARRAY[]::TEXT[], 1),
('replit.com', 'playground', 'Development', ARRAY[]::TEXT[], 1),
('stackblitz.com', 'playground', 'Development', ARRAY[]::TEXT[], 1),
('vercel.com', 'platform', 'Development', ARRAY[]::TEXT[], 1),
('netlify.com', 'platform', 'Development', ARRAY[]::TEXT[], 1),
('heroku.com', 'platform', 'Development', ARRAY[]::TEXT[], 1),
('docker.com', 'platform', 'Development', ARRAY[]::TEXT[], 1),
('kubernetes.io', 'platform', 'Development', ARRAY[]::TEXT[], 1),
('supabase.com', 'platform', 'Development', ARRAY[]::TEXT[], 1),
('firebase.google.com', 'platform', 'Development', ARRAY[]::TEXT[], 1),
('aws.amazon.com', 'platform', 'Development', ARRAY[]::TEXT[], 1),
('cloud.google.com', 'platform', 'Development', ARRAY[]::TEXT[], 1),
('azure.microsoft.com', 'platform', 'Development', ARRAY[]::TEXT[], 1),
('render.com', 'platform', 'Development', ARRAY[]::TEXT[], 1),
('railway.app', 'platform', 'Development', ARRAY[]::TEXT[], 1),
('fly.io', 'platform', 'Development', ARRAY[]::TEXT[], 1),
('gist.github.com', 'snippet', 'Development', ARRAY[]::TEXT[], 1),

-- Documentation
('developer.mozilla.org', 'reference', 'Documentation', ARRAY[]::TEXT[], 1),
('docs.github.com', 'docs', 'Documentation', ARRAY[]::TEXT[], 1),
('reactjs.org', 'docs', 'Documentation', ARRAY[]::TEXT[], 1),
('react.dev', 'docs', 'Documentation', ARRAY[]::TEXT[], 1),
('vuejs.org', 'docs', 'Documentation', ARRAY[]::TEXT[], 1),
('angular.io', 'docs', 'Documentation', ARRAY[]::TEXT[], 1),
('angular.dev', 'docs', 'Documentation', ARRAY[]::TEXT[], 1),
('svelte.dev', 'docs', 'Documentation', ARRAY[]::TEXT[], 1),
('nextjs.org', 'docs', 'Documentation', ARRAY[]::TEXT[], 1),
('nuxt.com', 'docs', 'Documentation', ARRAY[]::TEXT[], 1),
('astro.build', 'docs', 'Documentation', ARRAY[]::TEXT[], 1),
('typescriptlang.org', 'docs', 'Documentation', ARRAY[]::TEXT[], 1),
('nodejs.org', 'docs', 'Documentation', ARRAY[]::TEXT[], 1),
('docs.python.org', 'docs', 'Documentation', ARRAY[]::TEXT[], 1),
('docs.rs', 'docs', 'Documentation', ARRAY[]::TEXT[], 1),
('go.dev', 'docs', 'Documentation', ARRAY[]::TEXT[], 1),
('tailwindcss.com', 'docs', 'Documentation', ARRAY[]::TEXT[], 1),
('sass-lang.com', 'docs', 'Documentation', ARRAY[]::TEXT[], 1),
('webpack.js.org', 'docs', 'Documentation', ARRAY[]::TEXT[], 1),
('vitejs.dev', 'docs', 'Documentation', ARRAY[]::TEXT[], 1),
('eslint.org', 'docs', 'Documentation', ARRAY[]::TEXT[], 1),
('jestjs.io', 'docs', 'Documentation', ARRAY[]::TEXT[], 1),
('playwright.dev', 'docs', 'Documentation', ARRAY[]::TEXT[], 1),
('graphql.org', 'docs', 'Documentation', ARRAY[]::TEXT[], 1),
('prisma.io', 'docs', 'Documentation', ARRAY[]::TEXT[], 1),
('trpc.io', 'docs', 'Documentation', ARRAY[]::TEXT[], 1),

-- Design
('dribbble.com', 'showcase', 'Design', ARRAY[]::TEXT[], 1),
('behance.net', 'showcase', 'Design', ARRAY[]::TEXT[], 1),
('figma.com', 'tool', 'Design', ARRAY[]::TEXT[], 1),
('canva.com', 'tool', 'Design', ARRAY[]::TEXT[], 1),
('awwwards.com', 'showcase', 'Design', ARRAY[]::TEXT[], 1),
('designspiration.com', 'showcase', 'Design', ARRAY[]::TEXT[], 1),
('pinterest.com', 'showcase', 'Design', ARRAY[]::TEXT[], 1),
('unsplash.com', 'asset', 'Design', ARRAY[]::TEXT[], 1),
('pexels.com', 'asset', 'Design', ARRAY[]::TEXT[], 1),
('coolors.co', 'tool', 'Design', ARRAY[]::TEXT[], 1),
('fontpair.co', 'tool', 'Design', ARRAY[]::TEXT[], 1),
('fonts.google.com', 'asset', 'Design', ARRAY[]::TEXT[], 1),
('iconify.design', 'asset', 'Design', ARRAY[]::TEXT[], 1),
('heroicons.com', 'asset', 'Design', ARRAY[]::TEXT[], 1),
('lucide.dev', 'asset', 'Design', ARRAY[]::TEXT[], 1),

-- Research & Education
('arxiv.org', 'paper', 'Research', ARRAY[]::TEXT[], 1),
('scholar.google.com', 'search', 'Research', ARRAY[]::TEXT[], 1),
('researchgate.net', 'platform', 'Research', ARRAY[]::TEXT[], 1),
('semanticscholar.org', 'search', 'Research', ARRAY[]::TEXT[], 1),
('pubmed.ncbi.nlm.nih.gov', 'paper', 'Research', ARRAY[]::TEXT[], 1),
('nature.com', 'journal', 'Research', ARRAY[]::TEXT[], 1),
('science.org', 'journal', 'Research', ARRAY[]::TEXT[], 1),
('ieee.org', 'journal', 'Research', ARRAY[]::TEXT[], 1),
('acm.org', 'journal', 'Research', ARRAY[]::TEXT[], 1),
('wikipedia.org', 'encyclopedia', 'Reference', ARRAY[]::TEXT[], 1),
('britannica.com', 'encyclopedia', 'Reference', ARRAY[]::TEXT[], 1),
('coursera.org', 'course', 'Education', ARRAY[]::TEXT[], 1),
('udemy.com', 'course', 'Education', ARRAY[]::TEXT[], 1),
('edx.org', 'course', 'Education', ARRAY[]::TEXT[], 1),
('khanacademy.org', 'course', 'Education', ARRAY[]::TEXT[], 1),
('freecodecamp.org', 'course', 'Education', ARRAY[]::TEXT[], 1),
('codecademy.com', 'course', 'Education', ARRAY[]::TEXT[], 1),
('leetcode.com', 'practice', 'Education', ARRAY[]::TEXT[], 1),
('hackerrank.com', 'practice', 'Education', ARRAY[]::TEXT[], 1),
('exercism.org', 'practice', 'Education', ARRAY[]::TEXT[], 1),
('brilliant.org', 'course', 'Education', ARRAY[]::TEXT[], 1),
('skillshare.com', 'course', 'Education', ARRAY[]::TEXT[], 1),

-- AI & ML
('huggingface.co', 'platform', 'AI', ARRAY['machine-learning'], 1),
('openai.com', 'platform', 'AI', ARRAY['llm'], 1),
('anthropic.com', 'platform', 'AI', ARRAY['llm'], 1),
('kaggle.com', 'platform', 'AI', ARRAY['data-science'], 1),
('paperswithcode.com', 'platform', 'AI', ARRAY['machine-learning'], 1),
('replicate.com', 'platform', 'AI', ARRAY[]::TEXT[], 1),
('together.ai', 'platform', 'AI', ARRAY[]::TEXT[], 1),
('civitai.com', 'platform', 'AI', ARRAY['generative-ai'], 1),
('ollama.com', 'tool', 'AI', ARRAY['llm'], 1),

-- News & Media
('techcrunch.com', 'tech', 'News', ARRAY[]::TEXT[], 1),
('theverge.com', 'tech', 'News', ARRAY[]::TEXT[], 1),
('arstechnica.com', 'tech', 'News', ARRAY[]::TEXT[], 1),
('wired.com', 'tech', 'News', ARRAY[]::TEXT[], 1),
('news.ycombinator.com', 'tech', 'News', ARRAY[]::TEXT[], 1),
('bbc.com', 'general', 'News', ARRAY[]::TEXT[], 1),
('reuters.com', 'general', 'News', ARRAY[]::TEXT[], 1),
('nytimes.com', 'general', 'News', ARRAY[]::TEXT[], 1),
('theguardian.com', 'general', 'News', ARRAY[]::TEXT[], 1),
('washingtonpost.com', 'general', 'News', ARRAY[]::TEXT[], 1),
('bloomberg.com', 'business', 'News', ARRAY[]::TEXT[], 1),
('cnbc.com', 'business', 'News', ARRAY[]::TEXT[], 1),
('thenewstack.io', 'tech', 'News', ARRAY[]::TEXT[], 1),
('infoq.com', 'tech', 'News', ARRAY[]::TEXT[], 1),
('zdnet.com', 'tech', 'News', ARRAY[]::TEXT[], 1),

-- Articles & Blogs
('medium.com', 'blog', 'Articles', ARRAY[]::TEXT[], 1),
('substack.com', 'newsletter', 'Articles', ARRAY[]::TEXT[], 1),
('wordpress.com', 'blog', 'Articles', ARRAY[]::TEXT[], 1),
('blogger.com', 'blog', 'Articles', ARRAY[]::TEXT[], 1),
('ghost.org', 'blog', 'Articles', ARRAY[]::TEXT[], 1),
('mirror.xyz', 'blog', 'Articles', ARRAY[]::TEXT[], 1),
('beehiiv.com', 'newsletter', 'Articles', ARRAY[]::TEXT[], 1),

-- Social
('twitter.com', 'microblog', 'Social', ARRAY[]::TEXT[], 1),
('x.com', 'microblog', 'Social', ARRAY[]::TEXT[], 1),
('reddit.com', 'forum', 'Social', ARRAY[]::TEXT[], 1),
('linkedin.com', 'professional', 'Social', ARRAY[]::TEXT[], 1),
('facebook.com', 'social', 'Social', ARRAY[]::TEXT[], 1),
('instagram.com', 'social', 'Social', ARRAY[]::TEXT[], 1),
('mastodon.social', 'microblog', 'Social', ARRAY[]::TEXT[], 1),
('threads.net', 'microblog', 'Social', ARRAY[]::TEXT[], 1),
('discord.com', 'chat', 'Social', ARRAY[]::TEXT[], 1),
('slack.com', 'chat', 'Social', ARRAY[]::TEXT[], 1),
('bsky.app', 'microblog', 'Social', ARRAY[]::TEXT[], 1),

-- Video
('youtube.com', 'video', 'Video', ARRAY[]::TEXT[], 1),
('vimeo.com', 'video', 'Video', ARRAY[]::TEXT[], 1),
('twitch.tv', 'stream', 'Video', ARRAY[]::TEXT[], 1),
('loom.com', 'recording', 'Video', ARRAY[]::TEXT[], 1),
('dailymotion.com', 'video', 'Video', ARRAY[]::TEXT[], 1),

-- Productivity & Tools
('notion.so', 'tool', 'Productivity', ARRAY[]::TEXT[], 1),
('trello.com', 'tool', 'Productivity', ARRAY[]::TEXT[], 1),
('asana.com', 'tool', 'Productivity', ARRAY[]::TEXT[], 1),
('linear.app', 'tool', 'Productivity', ARRAY[]::TEXT[], 1),
('airtable.com', 'tool', 'Productivity', ARRAY[]::TEXT[], 1),
('miro.com', 'tool', 'Productivity', ARRAY[]::TEXT[], 1),
('clickup.com', 'tool', 'Productivity', ARRAY[]::TEXT[], 1),
('todoist.com', 'tool', 'Productivity', ARRAY[]::TEXT[], 1),
('obsidian.md', 'tool', 'Productivity', ARRAY[]::TEXT[], 1),
('excalidraw.com', 'tool', 'Productivity', ARRAY[]::TEXT[], 1),

-- Documents
('docs.google.com', 'document', 'Documents', ARRAY[]::TEXT[], 1),
('sheets.google.com', 'spreadsheet', 'Documents', ARRAY[]::TEXT[], 1),
('slides.google.com', 'presentation', 'Documents', ARRAY[]::TEXT[], 1),
('drive.google.com', 'storage', 'Documents', ARRAY[]::TEXT[], 1),
('dropbox.com', 'storage', 'Documents', ARRAY[]::TEXT[], 1),

-- Shopping
('amazon.com', 'marketplace', 'Shopping', ARRAY[]::TEXT[], 1),
('ebay.com', 'marketplace', 'Shopping', ARRAY[]::TEXT[], 1),
('etsy.com', 'marketplace', 'Shopping', ARRAY[]::TEXT[], 1),
('shopify.com', 'platform', 'Shopping', ARRAY[]::TEXT[], 1),

-- Finance
('finance.yahoo.com', 'portal', 'Finance', ARRAY[]::TEXT[], 1),
('investopedia.com', 'reference', 'Finance', ARRAY[]::TEXT[], 1),
('coinmarketcap.com', 'crypto', 'Finance', ARRAY[]::TEXT[], 1),
('coingecko.com', 'crypto', 'Finance', ARRAY[]::TEXT[], 1),

-- Podcasts & Audio
('spotify.com', 'streaming', 'Audio', ARRAY[]::TEXT[], 1),
('podcasts.apple.com', 'podcast', 'Audio', ARRAY[]::TEXT[], 1),
('soundcloud.com', 'streaming', 'Audio', ARRAY[]::TEXT[], 1)

ON CONFLICT (domain) DO NOTHING;
